name = "MaximumGeneratorProfitTCRDD"
uuid = "9929d651-aab0-4650-9216-2df6252268a4"
authors = ["abraham.alvarez.bustos <abraham.alvarez.bustos@invenialabs.co.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
